networkInterfaces: [
]

overrideMetricsUsingScriptFile: false

scriptTimeoutInSec: 60

scriptFiles:
  - osType: windows
    filePath: monitors/NetworkMonitor/scripts/windows-metrics.bat
  - osType: unixBase
    filePath: monitors/NetworkMonitor/scripts/unix-base-metrics.sh


# Add metrics to the ignoreMetricsDelta to ignore delta calculations for certain metrics.
# For eg. ignoreMetricsDelta: ["TCP|State|Bound","TCP|Segments Retransmitted"]
ignoreMetricsDelta: []

metricPrefix:  "Custom Metrics|Network|"

